# ============================================================
# Formality equivalence checking script
# ============================================================

proc get_env_or {var default} {
    if {[info exists ::env($var)] && $::env($var) ne ""} {
        return $::env($var)
    } else {
        return $default
    }
}

proc make_abs {path root} {
    if {[file pathtype $path] eq "absolute"} {
        return $path
    } else {
        return [file normalize [file join $root $path]]
    }
}

set PROJECT_ROOT [get_env_or PROJECT_ROOT [file normalize "."]]
set TOP_DESIGN   [get_env_or TOP_DESIGN "bit_serial_mac_unsigned"]
set RTL_LIST     [get_env_or RTL_LIST "$PROJECT_ROOT/dv/filelists/rtl.f"]
set NETLIST      [get_env_or SYN_NETLIST "$PROJECT_ROOT/syn/netlist/${TOP_DESIGN}_syn.v"]
set TARGET_LIB   [get_env_or FORMAL_TARGET_LIB ""]
set SVF_FILE     [get_env_or SVF_FILE "$PROJECT_ROOT/syn/work/${TOP_DESIGN}.svf"]

set REPORT_DIR "$PROJECT_ROOT/lec/reports"
set WORK_DIR   "$PROJECT_ROOT/lec/work"

file mkdir $REPORT_DIR
file mkdir $WORK_DIR

set RTL_LIST [make_abs $RTL_LIST $PROJECT_ROOT]
set NETLIST  [make_abs $NETLIST  $PROJECT_ROOT]
set SVF_FILE [make_abs $SVF_FILE $PROJECT_ROOT]

puts "============================================================"
puts "Formality LEC"
puts "TOP_DESIGN = $TOP_DESIGN"
puts "RTL_LIST   = $RTL_LIST"
puts "NETLIST    = $NETLIST"
puts "TARGET_LIB = $TARGET_LIB"
puts "SVF_FILE   = $SVF_FILE"
puts "============================================================"

# ------------------------------------------------------------
# Library
# ------------------------------------------------------------

read_db $TARGET_LIB

# ------------------------------------------------------------
# Read SVF generated by DC
# ------------------------------------------------------------

if {[file exists $SVF_FILE]} {
    set_svf $SVF_FILE
} else {
    puts "WARNING: SVF not found: $SVF_FILE"
}

# ------------------------------------------------------------
# Read golden RTL
# ------------------------------------------------------------

set rtl_files {}
set fp [open $RTL_LIST r]
while {[gets $fp line] >= 0} {
    set line [string trim $line]
    if {$line == ""} { continue }
    if {[string index $line 0] == "#"} { continue }
    lappend rtl_files [make_abs $line $PROJECT_ROOT]
}
close $fp

read_verilog -container r -libname WORK $rtl_files
set_top r:/WORK/$TOP_DESIGN

# ------------------------------------------------------------
# Read revised gate netlist
# ------------------------------------------------------------

read_verilog -container i -libname WORK $NETLIST
set_top i:/WORK/$TOP_DESIGN

# ------------------------------------------------------------
# Match and verify
# ------------------------------------------------------------

match
report_matched_points > "$REPORT_DIR/matched_points.rpt"
report_unmatched_points > "$REPORT_DIR/unmatched_points.rpt"

verify

report_failing_points > "$REPORT_DIR/failing_points.rpt"
report_passing_points > "$REPORT_DIR/passing_points.rpt"

exit