# ============================================================

# Frontend reference project environment

# Usage:

# source scripts/env.csh

# Must be sourced from project root: fe_ref_project/

# ============================================================

# ------------------------------------------------------------

# Basic check

# ------------------------------------------------------------

if (! -e Makefile) then
echo "[env.csh] ERROR: Please source this file from project root."
echo "[env.csh] Example:"
echo "          cd fe_ref_project"
echo "          source scripts/env.csh"
goto ENV_DONE
endif

# ------------------------------------------------------------

# Initialize environment modules if needed

# ------------------------------------------------------------

if (! $?MODULESHOME) then
if (-e /usr/share/Modules/init/csh) then
source /usr/share/Modules/init/csh
endif
endif

# ------------------------------------------------------------

# Read project variables from Makefile

# ------------------------------------------------------------

setenv FE_PROJECT_ROOT `make -s print-PROJECT_ROOT`
setenv PROJECT_ROOT "${FE_PROJECT_ROOT}"

setenv TOP_DESIGN     `make -s print-TOP_DESIGN`
setenv TB_TOP         `make -s print-TB_TOP`

setenv RTL_LIST       `make -s print-RTL_LIST`
setenv TB_LIST        `make -s print-TB_LIST`
setenv GATE_LIST      `make -s print-GATE_LIST`

setenv SYN_NETLIST    `make -s print-SYN_NETLIST`
setenv SYN_SDC        `make -s print-SYN_SDC`
setenv SYN_SDF        `make -s print-SYN_SDF`

setenv DC_TARGET_LIB  `make -s print-DC_TARGET_LIB`
setenv STD_CELL_VERILOG `make -s print-STD_CELL_VERILOG`

# Optional libraries for LEC / STA

setenv FORMAL_TARGET_LIB `make -s print-FORMAL_TARGET_LIB`
setenv PT_TARGET_LIB     `make -s print-PT_TARGET_LIB`
setenv PT_SETUP_LIB      `make -s print-PT_SETUP_LIB`
setenv PT_HOLD_LIB       `make -s print-PT_HOLD_LIB`
setenv TEMPUS_SETUP_LIB  `make -s print-TEMPUS_SETUP_LIB`
setenv TEMPUS_HOLD_LIB   `make -s print-TEMPUS_HOLD_LIB`

# SVF generated by Design Compiler, used by Formality

setenv SVF_FILE "${FE_PROJECT_ROOT}/syn/work/${TOP_DESIGN}.svf"

# ------------------------------------------------------------

# Read module names from config/tools.mk

# Empty module name means skip loading

# ------------------------------------------------------------

set XCELIUM_MODULE   = "`make -s print-XCELIUM_MODULE`"
set DC_MODULE        = "`make -s print-DC_MODULE`"
set SPYGLASS_MODULE  = "`make -s print-SPYGLASS_MODULE`"
set VERDI_MODULE     = "`make -s print-VERDI_MODULE`"

set FORMALITY_MODULE = "`make -s print-FORMALITY_MODULE`"
set PT_MODULE        = "`make -s print-PT_MODULE`"
set CONFORMAL_MODULE = "`make -s print-CONFORMAL_MODULE`"
set TEMPUS_MODULE    = "`make -s print-TEMPUS_MODULE`"

# ------------------------------------------------------------

# Load modules

# ------------------------------------------------------------

echo "[env.csh] Loading EDA modules..."

if ("$XCELIUM_MODULE" != "") then
module load $XCELIUM_MODULE
endif

if ("$DC_MODULE" != "") then
module load $DC_MODULE
endif

if ("$SPYGLASS_MODULE" != "") then
module load $SPYGLASS_MODULE
endif

if ("$VERDI_MODULE" != "") then
module load $VERDI_MODULE
endif

if ("$FORMALITY_MODULE" != "") then
module load $FORMALITY_MODULE
endif

if ("$PT_MODULE" != "") then
module load $PT_MODULE
endif

if ("$CONFORMAL_MODULE" != "") then
module load $CONFORMAL_MODULE
endif

if ("$TEMPUS_MODULE" != "") then
module load $TEMPUS_MODULE
endif

# ------------------------------------------------------------
# PrimeTime PTS M-2016 compatibility libraries
# ------------------------------------------------------------

if ("`make -s print-PT_MODULE`" == "synopsys/pts/M-2016.12-SP2") then
    setenv PTS_ROOT /NAS/cad/synopsys/pts/M-2016.12-SP2

    if (-d "$HOME/compat_lib") then
        if ($?LD_LIBRARY_PATH) then
            setenv LD_LIBRARY_PATH "$HOME/compat_lib:${PTS_ROOT}/linux64/pt/shlib:${PTS_ROOT}/linux64/syn/bin:${LD_LIBRARY_PATH}"
        else
            setenv LD_LIBRARY_PATH "$HOME/compat_lib:${PTS_ROOT}/linux64/pt/shlib:${PTS_ROOT}/linux64/syn/bin"
        endif
    else
        if ($?LD_LIBRARY_PATH) then
            setenv LD_LIBRARY_PATH "${PTS_ROOT}/linux64/pt/shlib:${PTS_ROOT}/linux64/syn/bin:${LD_LIBRARY_PATH}"
        else
            setenv LD_LIBRARY_PATH "${PTS_ROOT}/linux64/pt/shlib:${PTS_ROOT}/linux64/syn/bin"
        endif
    endif
endif

# ------------------------------------------------------------

# Tool commands

# ------------------------------------------------------------

setenv XRUN      `make -s print-XRUN`
setenv DC_SHELL  `make -s print-DC_SHELL`
setenv FM_SHELL  `make -s print-FM_SHELL`
setenv PT_SHELL  `make -s print-PT_SHELL`
setenv CONFORMAL `make -s print-CONFORMAL`
setenv TEMPUS    `make -s print-TEMPUS`

# ------------------------------------------------------------

# SpyGlass runtime workaround

# ------------------------------------------------------------

# This project found that SpyGlass P-2019.06 may load an old freetype

# from dotty/lib/Linux4. Preloading system freetype avoids:

# undefined symbol: FT_Done_MM_Var

setenv SPYGLASS_ROOT `make -s print-SPYGLASS_ROOT`
setenv SPYGLASS_HOME "${SPYGLASS_ROOT}/SPYGLASS_HOME"
setenv SPYGLASS_LD_PRELOAD `make -s print-SPYGLASS_PRELOAD`

# Do not force SPYGLASS_LD_LIBRARY_PATH here.

# For this SpyGlass version, forcing /lib64:/usr/lib64 may cause:

# undefined symbol: Tcl_VerifyChecksum

# ------------------------------------------------------------

# Friendly summary

# ------------------------------------------------------------

echo "============================================================"
echo "Frontend reference project environment loaded"
echo "PROJECT_ROOT       = ${FE_PROJECT_ROOT}"
echo "TOP_DESIGN         = ${TOP_DESIGN}"
echo "TB_TOP             = ${TB_TOP}"
echo ""
echo "RTL_LIST           = ${RTL_LIST}"
echo "GATE_LIST          = ${GATE_LIST}"
echo ""
echo "DC_TARGET_LIB      = ${DC_TARGET_LIB}"
echo "STD_CELL_VERILOG   = ${STD_CELL_VERILOG}"
echo ""
echo "SYN_NETLIST        = ${SYN_NETLIST}"
echo "SYN_SDC            = ${SYN_SDC}"
echo "SYN_SDF            = ${SYN_SDF}"
echo "SVF_FILE           = ${SVF_FILE}"
echo ""
echo "FORMAL_TARGET_LIB  = ${FORMAL_TARGET_LIB}"
echo "PT_TARGET_LIB      = ${PT_TARGET_LIB}"
echo ""
echo "Tool commands:"
echo "  XRUN             = ${XRUN}"
echo "  DC_SHELL         = ${DC_SHELL}"
echo "  FM_SHELL         = ${FM_SHELL}"
echo "  PT_SHELL         = ${PT_SHELL}"
echo "  CONFORMAL        = ${CONFORMAL}"
echo "  TEMPUS           = ${TEMPUS}"
echo "============================================================"

ENV_DONE:
